### ISSUE TITLE
Unable to select music packs (no option) 

### ISSUE THREAD

**Issue by The-Holy-Burrito** [Music-Expanded/music-expanded-framework#34]
As the title says, I am unable to pick two of the music packs (screenshot posted)
![Screenshot_20221123_022615](https://user-images.githubusercontent.com/118892078/203525508-469c3d88-0741-42f1-ac42-dfafc9cd5412.png)

Now I am running a lot of mods 279, so ill try and comb through them all to find the conflict, but in the meantime, I can post my logs. Thank you!

https://gist.github.com/f58235ab3ab7816287bc8c6b6c36f3c3   (link to logs)

**Comment by Praetorian1410** [comment]
I also have this issue (running more like 750 mods though, so I doubt my modlist will be of help).
@The-Holy-Burrito - are you also running Fluffy's Music Manager? Perhaps it's causing the issues...

**Comment by Caaz** [comment]
Really strange issue that we're trying to figure out at the moment actually. It's for sure a mod incompatibility it's just figuring it out is the trouble. @JustinMarshallElias also had this issue. 

Whatever's causing this is adding the blue "Music Expanded Core" I think, that isn't put there intentionally.

**Comment by Caaz** [comment]
GOOD NEWS EVERYONE. it's What's that mod incompatibility!

We'll work through resolving it

**Comment by Praetorian1410** [comment]
You work fast, nice job finding the culprit so quickly!
