### ISSUE TITLE
Core Sound File Size

### ISSUE THREAD

**Issue by TheLoneTec** [Music-Expanded/music-expanded-framework#44]
Here is a link to the converted files. Uploaded them to WeTransfer. https://we.tl/t-uqDDBtNbU4

All songs converted to .ogg to reduce file size to 425mb. Named the same, and had no issues so far.

**Comment by Caaz** [comment]
My nigga

**Comment by Caaz** [comment]
only complaint is that the man in black song; but I've got that one converted myself while testing some stuff so I can just slot that in. Does solve a problem we were having getting the files together. Thank you! I'll throw it in today.

**Comment by TheLoneTec** [comment]
oh did i miss one?

**Comment by Caaz** [comment]
yep but I got it no worries at all
